### ISSUE TITLE
Cargo workspace members cannot reference common files

### ISSUE THREAD

**Issue by drozdziak1** [nmattia/naersk#108]
`vcpkg`, one of my package's transitive dependencies, specifies a README located outside its crate directory, in its wider cargo workspace root. It appears that `naersk` didn't catch that.
```shell
error: failed to get `clap` as a dependency of package `cign v0.1.0 (/build/dummy-src)`

Caused by:
  failed to load source for dependency `clap`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to parse manifest at `/nix/store/ybindkbcy3d74hyjcc3kpygkdmdf8cwm-crates-io/vcpkg-0.2.9/Cargo.toml`

Caused by:
  readme file with name '../README.md' was not found
[naersk] cargo returned with exit code 101, exiting
builder for '/nix/store/b1j64hn8p0mgxjnb7nsbcrfqx2x7pjqj-cign-deps-0.1.0.drv' failed with exit code 101
cannot build derivation '/nix/store/grrd3cb3y8pdx60w9nhzrwmj14jm1nkq-cign-0.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/grrd3cb3y8pdx60w9nhzrwmj14jm1nkq-cign-0.1.0.drv' failed
```

**Comment by drozdziak1** [comment]
After prodding this some more `cargo-tree` tells me that I don't depend on `vcpkg` and it fails all the same no matter which dependency I remove from my `Cargo.toml`. Pinning an older `nightly` worked as a workaround.

**Comment by nmattia** [comment]
Hi, could you give more details? I've managed to build the package with this setup:

``` shell
 $  niv add NixOS/nixpkgs -b release-20.03
 $  niv add mcgoo/vcpkg-rs
 $  niv add nmattia/naersk
```

``` nix
# default.nix
let
  sources = import ./nix/sources.nix;
  pkgs = import sources.nixpkgs {};
  naersk = pkgs.callPackage sources.naersk {};
in
  naersk.buildPackage sources.vcpkg-rs
```



``` shell
building '/nix/store/g7ws0pszjllciz5n1wh9k7q05b0lslhr-rust-workspace-deps-unknown.drv'...
unpacking sources
unpacking source archive /nix/store/30w3x1f3c8gjybfh0sywr6dcvkqcqv1q-dummy-src
source root is dummy-src
patching sources
configuring
[naersk] cargo_version (read): 1.41.0
[naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
[naersk] cargo_release: --release
[naersk] cargo_options: -Z unstable-options
[naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
[naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
[naersk] RUST_TEST_THREADS: 8
[naersk] cargo_bins_jq_filter: .
[naersk] cargo_build_output_json (created): /build/tmp.RqKjupThO8
[naersk] crate_sources: /nix/store/cgas0klk8czpj2qzbr1af3vz0skwhflw-crates-io
[naersk] RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS (updated): --remap-path-prefix /nix/store/cgas0klk8czpj2qzbr1af3vz0skwhflw-crates-io=/sources
building
cargo -Z unstable-options build $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
   Compiling proc-macro2 v1.0.15
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.23
   Compiling version_check v0.9.2
   Compiling libc v0.2.71
   Compiling serde v1.0.110
   Compiling unicode-width v0.1.5
   Compiling ryu v1.0.4
   Compiling vcpkg v0.2.10 (/build/dummy-src/vcpkg)
   Compiling vec_map v0.8.1
   Compiling ansi_term v0.11.0
   Compiling unicode-segmentation v1.6.0
   Compiling strsim v0.8.0
   Compiling bitflags v1.0.3
   Compiling itoa v0.4.5
   Compiling semver-parser v0.7.0
   Compiling anyhow v1.0.31
   Compiling vcpkg_cli v0.2.4 (/build/dummy-src/vcpkg_cli)
   Compiling cargo-vcpkg v0.1.5 (/build/dummy-src/cargo-vcpkg)
   Compiling termcolor v1.1.0
   Compiling textwrap v0.11.0
   Compiling heck v0.3.1
   Compiling quote v1.0.6
   Compiling atty v0.2.14
   Compiling proc-macro-error-attr v0.4.12
   Compiling proc-macro-error v0.4.12
   Compiling clap v2.33.1
   Compiling syn-mid v0.5.0
   Compiling serde_derive v1.0.110
   Compiling structopt-derive v0.4.0
   Compiling structopt v0.3.7
   Compiling semver v0.9.0
   Compiling serde_json v1.0.53
   Compiling cargo_metadata v0.10.0
    Finished release [optimized] target(s) in 1m 50s
installing
/*stdin*\            : 31.29%   (83937280 => 26267801 bytes, /nix/store/gpcfaxkykzd3jzmp10xvb0ch01vz52g4-rust-workspace-deps-unknown/target.tar.zst) 
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/gpcfaxkykzd3jzmp10xvb0ch01vz52g4-rust-workspace-deps-unknown
strip is /nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/strip
patching script interpreter paths in /nix/store/gpcfaxkykzd3jzmp10xvb0ch01vz52g4-rust-workspace-deps-unknown
checking for references to /build/ in /nix/store/gpcfaxkykzd3jzmp10xvb0ch01vz52g4-rust-workspace-deps-unknown...
building '/nix/store/gy88ky3h50r2h4p48j9ifqlia4wms6j0-rust-workspace-unknown.drv'...
unpacking sources
unpacking source archive /nix/store/j94n74091gw05rq1ifb0px2jb35mcd0h-vcpkg-rs-src
source root is vcpkg-rs-src
patching sources
configuring
[naersk] cargo_version (read): 1.41.0
[naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
[naersk] cargo_release: --release
[naersk] cargo_options: -Z unstable-options
[naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
[naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
[naersk] RUST_TEST_THREADS: 8
[naersk] cargo_bins_jq_filter: select(.reason == "compiler-artifact" and .executable != null and .profile.test == false)
[naersk] cargo_build_output_json (created): /build/tmp.VvXGBhkwqY
[naersk] crate_sources: /nix/store/cgas0klk8czpj2qzbr1af3vz0skwhflw-crates-io
[naersk] RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS (updated): --remap-path-prefix /nix/store/cgas0klk8czpj2qzbr1af3vz0skwhflw-crates-io=/sources
[naersk] pre-installing dep /nix/store/gpcfaxkykzd3jzmp10xvb0ch01vz52g4-rust-workspace-deps-unknown
building
cargo -Z unstable-options build $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
   Compiling vcpkg v0.2.10 (/build/vcpkg-rs-src/vcpkg)
   Compiling cargo-vcpkg v0.1.5 (/build/vcpkg-rs-src/cargo-vcpkg)
   Compiling vcpkg_cli v0.2.4 (/build/vcpkg-rs-src/vcpkg_cli)
    Finished release [optimized] target(s) in 9.82s
installing
[naersk] Using file /build/tmp.VvXGBhkwqY to retrieve build (executable) products
[naersk] found executable vcpkg_cli -> /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown/bin/vcpkg_cli
[naersk] found executable cargo-vcpkg -> /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown/bin/cargo-vcpkg
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown
shrinking /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown/bin/cargo-vcpkg
shrinking /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown/bin/vcpkg_cli
strip is /nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown/bin 
patching script interpreter paths in /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown
checking for references to /build/ in /nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown...
/nix/store/d47rg1vgm8qqs42b9mjmajsywvsri0cf-rust-workspace-unknown
```

**Comment by evanjs** [comment]
I am getting this issue on a private repository with some private submodules.
The path, however, is absolute and _does_ appear in the nix store.

```
error: failed to read `/nix/store/q3z3s15xr0rvbbhjhkj51ggkyjrfjz80-source/Cargo.toml`
error: failed to read `/nix/store/q3z3s15xr0rvbbhjhkj51ggkyjrfjz80-source/Cargo.toml`


Caused by:
Caused by:
  No such file or directory (os error 2)
  No such file or directory (os error 2)
[naersk] cargo returned with exit code 101, exiting
[naersk] cargo returned with exit code 101, exiting
```

Wondering if there's an easy way to get a minimal reproducible example...

**Comment by yusdacra** [comment]
I believe I also encountered this error. For me it's with a submodule:
```
builder for '/nix/store/m2c7hpwrcpaky8wj13srd87xj212bk62-harmony_rust_sdk-0.2.1.drv' failed with exit code 101; last 10 log lines:
     Compiling tonic-build v0.3.1
     Compiling harmony_rust_sdk v0.2.1 (/build/source)
  error: failed to run custom build command for `harmony_rust_sdk v0.2.1 (/build/source)`

  Caused by:
    process didn't exit successfully: `/build/source/target/debug/build/harmony_rust_sdk-e1bf2448e7cea35d/build-script-build` (exit code: 101)
    --- stderr
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: protocol: warning: directory does not exist.\nCould not make proto path relative: harmonytypes/v1/types.proto: No such file or directory\n" }', build.rs:30:10
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  [naersk] cargo returned with exit code 101, exiting
```
where `protocol` is a submodule in my `root` (`src` is the same).

You can see the issue by cloning <https://github.com/harmony-development/harmony_rust_sdk>, switching to the `ci/nix` branch and building with `nix build .#harmony_rust_sdk-tests -L` (or `nix-build nix/default.nix`). Dev shell setups cachix cache so it will be faster if you do it within the shell.

**Comment by nmattia** [comment]
Hi, sorry for the delay. Is there any chance you can provide a minimal reproducible example? `harmony_rust_sdk` is fairly big

**Comment by yusdacra** [comment]
> Hi, sorry for the delay. Is there any chance you can provide a minimal reproducible example? `harmony_rust_sdk` is fairly big

Sure, I will make a repo with an MRE.

**Comment by yusdacra** [comment]
I have made a minimal example https://github.com/yusdacra/naersk_bug here. Just clone it and switch to the `submodule` branch. My Nix version is `2.4pre20210326_dd77f71` and the nixpkgs I used is on commit `6fc2b7ecc2a167ce6a6902d5417daf1fa5cac777`.

```
mre_naersk> unpacking sources
mre_naersk> unpacking source archive /nix/store/ljam2qj5af3cyhc00mf4yspaipz1cc5l-source
mre_naersk> source root is source
mre_naersk> patching sources
mre_naersk> configuring
mre_naersk> [naersk] cargo_version (read): 1.50.0
mre_naersk> [naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
mre_naersk> [naersk] cargo_release: --release
mre_naersk> [naersk] cargo_options: -Z unstable-options
mre_naersk> [naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
mre_naersk> [naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
mre_naersk> [naersk] RUST_TEST_THREADS: 4
mre_naersk> [naersk] cargo_bins_jq_filter: select(.reason == "compiler-artifact" and .executable != null and .profile.test == false)
mre_naersk> [naersk] cargo_build_output_json (created): /build/tmp.P3yhtVvSPD
mre_naersk> [naersk] crate_sources: /nix/store/ipgwnyr55zyrm71fkjj27b51gh8qynhy-crates-io
mre_naersk> [naersk] RUSTFLAGS:
mre_naersk> [naersk] CARGO_BUILD_RUSTFLAGS:
mre_naersk> [naersk] CARGO_BUILD_RUSTFLAGS (updated): --remap-path-prefix /nix/store/ipgwnyr55zyrm71fkjj27b51gh8qynhy-crates-io=/sources
mre_naersk> [naersk] pre-installing dep /nix/store/kzq6cab2rzwb6hyy9681slv2vwxnyzc4-mre_naersk-deps-0.1.0
mre_naersk> building
mre_naersk> cargo -Z unstable-options build $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
mre_naersk>    Compiling mre_naersk v0.1.0 (/build/source)
mre_naersk> error: failed to run custom build command for `mre_naersk v0.1.0 (/build/source)`
mre_naersk> Caused by:
mre_naersk>   process didn't exit successfully: `/build/source/target/release/build/mre_naersk-265e47b6b59688af/build-script-build` (exit code: 101)
mre_naersk>   --- stderr
mre_naersk>   thread 'main' panicked at 'can't compile protos: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/harmonytypes/v1/types.proto: No such file or directory\n" }', build.rs:2:92
mre_naersk>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mre_naersk> [naersk] cargo returned with exit code 101, exiting
error: builder for '/nix/store/jkc43r04k3871lrs1fym54bgim2mlyr9-mre_naersk-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       > cargo -Z unstable-options build $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
       >    Compiling mre_naersk v0.1.0 (/build/source)
       > error: failed to run custom build command for `mre_naersk v0.1.0 (/build/source)`
       >
       > Caused by:
       >   process didn't exit successfully: `/build/source/target/release/build/mre_naersk-265e47b6b59688af/build-script-build` (exit code: 101)
       >   --- stderr
       >   thread 'main' panicked at 'can't compile protos: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/harmonytypes/v1/types.proto: No such file or directory\n" }', build.rs:2:92
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > [naersk] cargo returned with exit code 101, exiting
       For full logs, run 'nix log /nix/store/jkc43r04k3871lrs1fym54bgim2mlyr9-mre_naersk-0.1.0.drv'.
```

**Comment by yusdacra** [comment]
> I have made a minimal example [yusdacra/naersk_bug](https://github.com/yusdacra/naersk_bug) here. Just clone it and switch to the `submodule` branch. My Nix version is `2.4pre20210326_dd77f71` and the nixpkgs I used is on commit `6fc2b7ecc2a167ce6a6902d5417daf1fa5cac777`.
> 
> ```
> mre_naersk> unpacking sources
> mre_naersk> unpacking source archive /nix/store/ljam2qj5af3cyhc00mf4yspaipz1cc5l-source
> mre_naersk> source root is source
> mre_naersk> patching sources
> mre_naersk> configuring
> mre_naersk> [naersk] cargo_version (read): 1.50.0
> mre_naersk> [naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
> mre_naersk> [naersk] cargo_release: --release
> mre_naersk> [naersk] cargo_options: -Z unstable-options
> mre_naersk> [naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
> mre_naersk> [naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
> mre_naersk> [naersk] RUST_TEST_THREADS: 4
> mre_naersk> [naersk] cargo_bins_jq_filter: select(.reason == "compiler-artifact" and .executable != null and .profile.test == false)
> mre_naersk> [naersk] cargo_build_output_json (created): /build/tmp.P3yhtVvSPD
> mre_naersk> [naersk] crate_sources: /nix/store/ipgwnyr55zyrm71fkjj27b51gh8qynhy-crates-io
> mre_naersk> [naersk] RUSTFLAGS:
> mre_naersk> [naersk] CARGO_BUILD_RUSTFLAGS:
> mre_naersk> [naersk] CARGO_BUILD_RUSTFLAGS (updated): --remap-path-prefix /nix/store/ipgwnyr55zyrm71fkjj27b51gh8qynhy-crates-io=/sources
> mre_naersk> [naersk] pre-installing dep /nix/store/kzq6cab2rzwb6hyy9681slv2vwxnyzc4-mre_naersk-deps-0.1.0
> mre_naersk> building
> mre_naersk> cargo -Z unstable-options build $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
> mre_naersk>    Compiling mre_naersk v0.1.0 (/build/source)
> mre_naersk> error: failed to run custom build command for `mre_naersk v0.1.0 (/build/source)`
> mre_naersk> Caused by:
> mre_naersk>   process didn't exit successfully: `/build/source/target/release/build/mre_naersk-265e47b6b59688af/build-script-build` (exit code: 101)
> mre_naersk>   --- stderr
> mre_naersk>   thread 'main' panicked at 'can't compile protos: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/harmonytypes/v1/types.proto: No such file or directory\n" }', build.rs:2:92
> mre_naersk>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> mre_naersk> [naersk] cargo returned with exit code 101, exiting
> error: builder for '/nix/store/jkc43r04k3871lrs1fym54bgim2mlyr9-mre_naersk-0.1.0.drv' failed with exit code 101;
>        last 10 log lines:
>        > cargo -Z unstable-options build $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
>        >    Compiling mre_naersk v0.1.0 (/build/source)
>        > error: failed to run custom build command for `mre_naersk v0.1.0 (/build/source)`
>        >
>        > Caused by:
>        >   process didn't exit successfully: `/build/source/target/release/build/mre_naersk-265e47b6b59688af/build-script-build` (exit code: 101)
>        >   --- stderr
>        >   thread 'main' panicked at 'can't compile protos: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/harmonytypes/v1/types.proto: No such file or directory\n" }', build.rs:2:92
>        >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>        > [naersk] cargo returned with exit code 101, exiting
>        For full logs, run 'nix log /nix/store/jkc43r04k3871lrs1fym54bgim2mlyr9-mre_naersk-0.1.0.drv'.
> ```

Apparently the cause of this was that git submodules were not being put in `source` because of flakes. The workaround is to use `builtins.fetchGit` to fetch source from your repository (and keeping an input for it in your inputs). Like so:

```nix
{
	inputs.selfDup = {
		url = "<url>";
		flake = false;
	};

	outputs = inputs: {
		#...
		# then in source fetching
		src = builtins.fetchGit {
			url = "<url>";
			rev = inputs.selfDup.rev;
			allRefs = true; # make sure all branches will work
			submodules = true;
		};
		#...
	};
}
```
